### ISSUE TITLE
Can't run as a daemon

### ISSUE THREAD

**Issue by profburke** [lukeredpath/mimic#3]
I'm using Ruby 1.8.7 on OS X.  I tried to run Mimic as a daemon as shown in Readme.md.  However, on running the script I get the following:

./startmimic.rb:6: undefined method `daemonize' for Mimic:Module (NoMethodError)

Below is the a listing of startmimic.rb:
# !/usr/bin/env ruby

require 'rubygems'
require 'mimic'

Mimic.daemonize({:port => 11988, :remote_configuration_path => '/api'})

**Comment by lukeredpath** [comment]
Oops, the daemonize function was removed; I've updated the README. Here's a script that will work using the daemons gem:

``` ruby
#!/usr/bin/env ruby
require 'mimic'
require 'daemons'

Daemons.run_proc("mimic") do
  Mimic.mimic(:port => 11988, :fork => false) do
    # configure your stubs here
  end
end
```

**Comment by profburke** [comment]
Thanks for the quick response.  I had looked through the source code and had noted the lack of a daemonize method, but for some reason I can't recall thought mimic inherited it from somewhere.

In order for the rest of the README to work, I would suggest one change in the code you posted above:

<pre>
#!/usr/bin/env ruby
require 'mimic'
require 'daemons'

Daemons.run_proc("mimic") do
  Mimic.mimic(:port => 11988, :fork => false<strong>, :remote_configuration_path => '/api'</strong>) do
    # configure your stubs here
  end
end
</pre>


Anyway, now I just have to puzzle out why <code>./startmimic.rb stop</code> doesn't actually stop the server :).

Thanks again!
